name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Vercel
        run: npx vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        env:
          VERCEL_ORG_ID: team_6TnBl6VXyzY45Fd3qP1KdIco
          VERCEL_PROJECT_ID: prj_gE46x5IAuhcOshhfhM0m21k62mFW
